on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: ajacr2.azurecr.io
        username: ${{ secrets.acr_ajAcr2_username }}
        password: ${{ secrets.acr_ajAcr2_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t ajacr2.azurecr.io/bugbash16215026:${{ github.sha }}
        docker push ajacr2.azurecr.io/bugbash16215026:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_bugbash162_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep bugbash16213959 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace bugbash16213959`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: bugbash16213959
        container-registry-url: ajacr2.azurecr.io
        container-registry-username: ${{ secrets.acr_ajAcr2_username }}
        container-registry-password: ${{ secrets.acr_ajAcr2_password }}
        secret-name: bugbash1621dockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: bugbash16213959
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          ajacr2.azurecr.io/bugbash16215026:${{ github.sha }}
        imagepullsecrets: |
          bugbash1621dockerauth
